# Generated by Django 4.2.11 on 2025-04-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='apartment_type',
            field=models.CharField(choices=[('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('50000', '5000'), ('6000', '6000'), ('7000', '7000'), ('8000', '8000'), ('9000', '9000'), ('10000', '10000')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='bedroomes_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='modular_kitchen',
            field=models.CharField(max_length=10),
        ),
    ]
