# Generated by Django 4.2.11 on 2025-04-13 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_alter_checkout_options_checkout_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
